import type { Metadata } from "next";
import { Crimson_Text } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const OldenburgFont = Crimson_Text({
  weight: ['400', '600', '700'],
  style: 'normal',
  fallback: ['serif'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OldenburgFont.className}  antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
